# ДЗ5. CTE-pipeline ознак для ML на Olist

Датасет [Olist Brazilian E-Commerce](https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce), версія 2 на Kaggle, ліцензія CC BY-NC-SA 4.0. Використано п'ять повних таблиць: клієнти, замовлення, позиції, товари й продавці.

## Завдання 1. Setup і typed-схема Olist

PostgreSQL 16 локально запускає `pgserver`. У Colab стоїть Python 3.13, під який `pgserver` не має збірок, тому там setup-клітинка ставить PostgreSQL з apt.

In [1]:
import subprocess
import sys

subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'psycopg2-binary', 'sqlalchemy>=2.0,<2.1', 'pandas',
                'kagglehub'], check=True)

import contextlib
import hashlib
import io
import re
import shutil
from pathlib import Path

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.exc import DBAPIError


def start_postgres() -> str:
    if sys.version_info < (3, 13):
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'pgserver'], check=True)
        import pgserver
        return pgserver.get_server('/tmp/hw5_pg', cleanup_mode='stop').get_uri()

    if shutil.which('apt-get') is None:
        raise RuntimeError('pgserver не має збірок для Python 3.13: запустіть ноутбук на Python 3.12 або в Colab')
    subprocess.run(
        'DEBIAN_FRONTEND=noninteractive apt-get -qq update '
        '&& DEBIAN_FRONTEND=noninteractive apt-get -qq install -y postgresql > /dev/null',
        shell=True, check=True,
    )
    subprocess.run(['service', 'postgresql', 'start'], check=True, capture_output=True)
    subprocess.run(
        ['runuser', '-u', 'postgres', '--', 'psql', '-qc', "ALTER USER postgres PASSWORD 'postgres'"],
        check=True,
    )
    return 'postgresql+psycopg2://postgres:postgres@localhost:5432/postgres'


# SET TIME ZONE діяв би лише на одне з'єднання пулу, а options - на кожне нове
engine = create_engine(start_postgres(), future=True, connect_args={'options': '-c TimeZone=UTC'})


def run_sql(sql: str, **params) -> None:
    with engine.begin() as conn:
        conn.execute(text(sql), params)


def q(sql: str, **params) -> pd.DataFrame:
    with engine.connect() as conn:
        return pd.read_sql_query(text(sql), conn, params=params)


def explain(sql: str) -> list[str]:
    with engine.connect() as conn:
        return [row[0] for row in conn.execute(text('EXPLAIN (ANALYZE, BUFFERS) ' + sql))]


pd.set_option('display.max_columns', 30)
pd.set_option('display.max_colwidth', 80)
pd.set_option('display.width', 200)

with engine.connect() as conn:
    print('PostgreSQL', conn.execute(text('SHOW server_version')).scalar_one())

PostgreSQL 16.2

Дані завантажує `kagglehub` із закріпленою версією датасету, без облікових даних Kaggle, а SHA-256 кожного файлу звіряється з очікуваним.

In [2]:
OLIST_HANDLE = 'olistbr/brazilian-ecommerce/versions/2'
OLIST_FILES = {
    'olist_customers_raw':   ('olist_customers_dataset.csv',   '983a422239e1712ded753b3bf9ecf47dc73f144d306029dcfa99e70a226883d2'),
    'olist_orders_raw':      ('olist_orders_dataset.csv',      '8df58ef3d2d7e9944010f7beecd9b75367f5588ec6e3c91cec19ae3345ef9ecf'),
    'olist_order_items_raw': ('olist_order_items_dataset.csv', '0bc4d068c4fe38cbb01bd90e8746e3c613fe7b4baef75fab7b0e329701c3e279'),
    'olist_products_raw':    ('olist_products_dataset.csv',    '3e6569628a17fbc75fd206ee357b59e20364b9afa90f5b6cd5b4d624c58aa9cc'),
    'olist_sellers_raw':     ('olist_sellers_dataset.csv',     '1f643d2b950373b85735e7794b20986f528d7a000432e7c6f9bcbb44d0846a0e'),
}


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def files_ok(folder: Path) -> bool:
    return all(
        (folder / name).exists() and sha256_of(folder / name) == digest
        for name, digest in OLIST_FILES.values()
    )


with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
    import kagglehub
    dataset_dir = Path(kagglehub.dataset_download(OLIST_HANDLE))
if not files_ok(dataset_dir):
    raise ValueError('файли з Kaggle відрізняються від очікуваних')
print(f'Olist v2: {len(OLIST_FILES)} файлів, sha256 збігається')

Olist v2: 5 файлів, sha256 збігається

Raw-шар читається як текст (`dtype=str`), щоб CSV потрапив у базу буквально, а всі приведення типів відбулися в SQL під час переносу.

In [3]:
for table_name, (file_name, _) in OLIST_FILES.items():
    df = pd.read_csv(dataset_dir / file_name, dtype=str, keep_default_na=False, na_values=[''])
    df.to_sql(table_name, engine, if_exists='replace', index=False, chunksize=10_000, method='multi')
    print(f'{table_name:<23} {df.shape}')

olist_customers_raw     (99441, 5)

olist_orders_raw        (99441, 8)

olist_order_items_raw   (112650, 7)

olist_products_raw      (32951, 9)
olist_sellers_raw       (3095, 4)

Typed-схема відповідає завданню. Від себе додано індекс на `customer_unique_id`, за яким фінальний `SELECT` з'єднує клієнтів з ознаками покупця, і `ANALYZE` після завантаження, щоб `EXPLAIN` мав статистику.

In [4]:
run_sql("""
DROP MATERIALIZED VIEW IF EXISTS mv_olist_customer_features CASCADE;
DROP TABLE IF EXISTS hw5_referrals     CASCADE;
DROP TABLE IF EXISTS olist_order_items CASCADE;
DROP TABLE IF EXISTS olist_orders      CASCADE;
DROP TABLE IF EXISTS olist_customers   CASCADE;
DROP TABLE IF EXISTS olist_products    CASCADE;
DROP TABLE IF EXISTS olist_sellers     CASCADE;

CREATE TABLE olist_customers (
    customer_id              TEXT PRIMARY KEY,
    customer_unique_id       TEXT NOT NULL,
    customer_zip_code_prefix INTEGER,
    customer_city            TEXT,
    customer_state           CHAR(2) NOT NULL
);

CREATE TABLE olist_orders (
    order_id                      TEXT PRIMARY KEY,
    customer_id                   TEXT NOT NULL REFERENCES olist_customers(customer_id),
    order_status                  TEXT NOT NULL,
    order_purchase_timestamp      TIMESTAMP NOT NULL,
    order_approved_at             TIMESTAMP,
    order_delivered_carrier_date  TIMESTAMP,
    order_delivered_customer_date TIMESTAMP,
    order_estimated_delivery_date TIMESTAMP,
    CHECK (order_status IN (
        'created', 'approved', 'invoiced', 'processing',
        'shipped', 'delivered', 'unavailable', 'canceled'
    ))
);

CREATE TABLE olist_products (
    product_id                 TEXT PRIMARY KEY,
    product_category_name      TEXT,
    product_name_length        INTEGER CHECK (product_name_length IS NULL OR product_name_length >= 0),
    product_description_length INTEGER CHECK (product_description_length IS NULL OR product_description_length >= 0),
    product_photos_qty         INTEGER CHECK (product_photos_qty IS NULL OR product_photos_qty >= 0),
    product_weight_g           INTEGER CHECK (product_weight_g IS NULL OR product_weight_g >= 0),
    product_length_cm          INTEGER CHECK (product_length_cm IS NULL OR product_length_cm >= 0),
    product_height_cm          INTEGER CHECK (product_height_cm IS NULL OR product_height_cm >= 0),
    product_width_cm           INTEGER CHECK (product_width_cm IS NULL OR product_width_cm >= 0)
);

CREATE TABLE olist_sellers (
    seller_id              TEXT PRIMARY KEY,
    seller_zip_code_prefix INTEGER,
    seller_city            TEXT,
    seller_state           CHAR(2) NOT NULL
);

CREATE TABLE olist_order_items (
    order_id            TEXT NOT NULL REFERENCES olist_orders(order_id),
    order_item_id       INTEGER NOT NULL,
    product_id          TEXT REFERENCES olist_products(product_id),
    seller_id           TEXT REFERENCES olist_sellers(seller_id),
    shipping_limit_date TIMESTAMP,
    price               NUMERIC(12, 2) CHECK (price IS NULL OR price >= 0),
    freight_value       NUMERIC(12, 2) CHECK (freight_value IS NULL OR freight_value >= 0),
    PRIMARY KEY (order_id, order_item_id)
);

CREATE INDEX idx_olist_customers_unique_id ON olist_customers (customer_unique_id);
""")

In [5]:
run_sql("""
INSERT INTO olist_customers
SELECT
    customer_id,
    customer_unique_id,
    customer_zip_code_prefix::INTEGER,
    customer_city,
    customer_state::CHAR(2)
FROM olist_customers_raw;

INSERT INTO olist_orders
SELECT
    order_id,
    customer_id,
    order_status,
    order_purchase_timestamp::TIMESTAMP,
    order_approved_at::TIMESTAMP,
    order_delivered_carrier_date::TIMESTAMP,
    order_delivered_customer_date::TIMESTAMP,
    order_estimated_delivery_date::TIMESTAMP
FROM olist_orders_raw;

INSERT INTO olist_products
SELECT
    product_id,
    product_category_name,
    product_name_lenght::INTEGER,
    product_description_lenght::INTEGER,
    product_photos_qty::INTEGER,
    product_weight_g::INTEGER,
    product_length_cm::INTEGER,
    product_height_cm::INTEGER,
    product_width_cm::INTEGER
FROM olist_products_raw;

INSERT INTO olist_sellers
SELECT
    seller_id,
    seller_zip_code_prefix::INTEGER,
    seller_city,
    seller_state::CHAR(2)
FROM olist_sellers_raw;

INSERT INTO olist_order_items
SELECT
    order_id,
    order_item_id::INTEGER,
    product_id,
    seller_id,
    shipping_limit_date::TIMESTAMP,
    price::NUMERIC(12, 2),
    freight_value::NUMERIC(12, 2)
FROM olist_order_items_raw;

ANALYZE olist_customers, olist_orders, olist_order_items, olist_products, olist_sellers;
""")

### Smoke-test кількості рядків

In [6]:
q('''
SELECT 'customers' AS table_name,
       (SELECT COUNT(*) FROM olist_customers_raw) AS raw_rows,
       (SELECT COUNT(*) FROM olist_customers)     AS typed_rows
UNION ALL
SELECT 'orders', (SELECT COUNT(*) FROM olist_orders_raw), (SELECT COUNT(*) FROM olist_orders)
UNION ALL
SELECT 'order_items', (SELECT COUNT(*) FROM olist_order_items_raw), (SELECT COUNT(*) FROM olist_order_items)
UNION ALL
SELECT 'products', (SELECT COUNT(*) FROM olist_products_raw), (SELECT COUNT(*) FROM olist_products)
UNION ALL
SELECT 'sellers', (SELECT COUNT(*) FROM olist_sellers_raw), (SELECT COUNT(*) FROM olist_sellers)
ORDER BY table_name
''')

    table_name  raw_rows  typed_rows
0    customers     99441       99441
1  order_items    112650      112650
2       orders     99441       99441
3     products     32951       32951
4      sellers      3095        3095

Усі п'ять typed-таблиць мають стільки ж рядків, скільки raw: по 99 441 клієнту й замовленню, 112 650 позицій, 32 951 товар і 3 095 продавців. Відгуки цьому pipeline не потрібні, і їх не завантажено.

## Завдання 2. CTE-chain pipeline

### Гранулярність: `customer_id` чи покупець

Шаблон рахує ознаки за `customer_id`. Спершу варто перевірити, що цей ідентифікатор означає в Olist:

In [7]:
q('''
SELECT (SELECT COUNT(*) FROM olist_customers)                          AS customer_ids,
       (SELECT COUNT(DISTINCT customer_unique_id) FROM olist_customers) AS buyers,
       (SELECT MAX(n) FROM (SELECT COUNT(*) AS n FROM olist_orders GROUP BY customer_id) AS per_id)
                                                                        AS max_orders_per_customer_id,
       (SELECT MAX(n) FROM (SELECT COUNT(*) AS n
                              FROM olist_orders AS o
                              JOIN olist_customers AS c ON c.customer_id = o.customer_id
                             GROUP BY c.customer_unique_id) AS per_buyer)
                                                                        AS max_orders_per_buyer
''')

   customer_ids  buyers  max_orders_per_customer_id  max_orders_per_buyer
0         99441   96096                           1                    17

99 441 `customer_id` належать 96 096 покупцям. Жоден `customer_id` не має більше одного замовлення, а в одного покупця їх до 17: в Olist `customer_id` фактично ідентифікує замовлення. Ознаки за ним вироджуються: `frequency` завжди 1, `cancellation_rate` буває 0 або 1, а 30-денний середній чек дорівнює сумі єдиного замовлення.

Тому pipeline рахує ознаки для покупця (`customer_unique_id`) і повертає рядок на кожен `customer_id` з ознаками його покупця. Так MV зберігає ключ `customer_id`, за яким її шукатимуть інші таблиці, а ознаки мають зміст. Для навчання моделі з результату треба брати один рядок на покупця, як у розподілах нижче, інакше покупець із 17 замовленнями потрапить у вибірку 17 разів.

### Pipeline

Вісім stages, кожен з однією відповідальністю і коментарем `-- Stage N`. Stage 1 один раз зводить позиції до замовлень, і з нього читають stages 2, 4 і 5. Stage 6 знову йде до позицій, бо категорія належить товару, а не замовленню. Фінальний `SELECT` бере кожен `customer_id` і через `LEFT JOIN` приєднує ознаки його покупця.

SQL лежить в одній змінній `FEATURE_PIPELINE`, і саме цей текст далі стає materialized view та йде в `EXPLAIN`.

In [8]:
FEATURE_PIPELINE = """
WITH
reference_date AS (
    -- Stage 0: stable reference date for the historical dataset
    SELECT (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    -- Stage 1: one row per order with buyer id, status and order total
    SELECT
        c.customer_unique_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp AS order_ts,
        o.order_purchase_timestamp::DATE AS order_date,
        COALESCE(SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        ), 0)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    JOIN olist_customers AS c
        ON c.customer_id = o.customer_id
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        c.customer_unique_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp
),
stage2_rfm AS (
    -- Stage 2: RFM features per buyer
    SELECT
        s.customer_unique_id,
        (rd.as_of_date - MAX(s.order_date))::INTEGER AS recency_days,
        COUNT(*) AS frequency,
        SUM(s.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(s.order_date) AS first_order_date
    FROM stage1_orders_total AS s
    CROSS JOIN reference_date AS rd
    GROUP BY s.customer_unique_id, rd.as_of_date
),
stage3_cohort AS (
    -- Stage 3: cohort quarter from the first order date
    SELECT
        r.*,
        DATE_TRUNC('quarter', r.first_order_date)::DATE AS cohort_quarter
    FROM stage2_rfm AS r
),
stage4_rolling_aov AS (
    -- Stage 4: rolling 30-day average order value, latest order flagged
    SELECT
        s.customer_unique_id,
        s.order_id,
        s.order_ts,
        s.order_total,
        AVG(s.order_total) OVER (
            PARTITION BY s.customer_unique_id
            ORDER BY s.order_ts
            RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
        )::NUMERIC(12, 2) AS avg_order_value_30d,
        ROW_NUMBER() OVER (
            PARTITION BY s.customer_unique_id
            ORDER BY s.order_ts DESC, s.order_id DESC
        ) AS rn_recent
    FROM stage1_orders_total AS s
),
stage5_cancel_rate AS (
    -- Stage 5: cancellation rate per buyer
    SELECT
        customer_unique_id,
        AVG(
            CASE WHEN order_status = 'canceled' THEN 1.0 ELSE 0.0 END
        )::NUMERIC(6, 4) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_unique_id
),
stage6_category_revenue AS (
    -- Stage 6: revenue by buyer and product category
    SELECT
        c.customer_unique_id,
        COALESCE(p.product_category_name, '(unknown)') AS product_category_name,
        SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS o
    JOIN olist_customers AS c
        ON c.customer_id = o.customer_id
    JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    LEFT JOIN olist_products AS p
        ON p.product_id = oi.product_id
    GROUP BY c.customer_unique_id, COALESCE(p.product_category_name, '(unknown)')
),
stage7_preferred_category AS (
    -- Stage 7: preferred category per buyer via top-1 ranking
    SELECT
        customer_unique_id,
        product_category_name,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_unique_id
                ORDER BY cr.category_revenue DESC, cr.product_category_name COLLATE "C"
            ) AS rn
        FROM stage6_category_revenue AS cr
    ) AS ranked
    WHERE rn = 1
)
SELECT
    c.customer_id,
    c.customer_unique_id,
    c.customer_state,
    (coh.customer_unique_id IS NOT NULL) AS has_orders,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0)::NUMERIC(12, 2) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(aov.avg_order_value_30d, 0)::NUMERIC(12, 2) AS avg_order_value_30d_recent,
    COALESCE(cancel.cancellation_rate, 0)::NUMERIC(6, 4) AS cancellation_rate,
    COALESCE(pc.product_category_name, '(none)') AS preferred_category,
    COALESCE(pc.category_revenue, 0)::NUMERIC(12, 2) AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON coh.customer_unique_id = c.customer_unique_id
LEFT JOIN stage4_rolling_aov AS aov
    ON aov.customer_unique_id = c.customer_unique_id
   AND aov.rn_recent = 1
LEFT JOIN stage5_cancel_rate AS cancel
    ON cancel.customer_unique_id = c.customer_unique_id
LEFT JOIN stage7_preferred_category AS pc
    ON pc.customer_unique_id = c.customer_unique_id
"""

q(FEATURE_PIPELINE + """
ORDER BY monetary DESC NULLS LAST, c.customer_id
LIMIT 10
""")

,customer_id,customer_unique_id,customer_state,has_orders,recency_days,frequency,monetary,first_order_date,cohort_quarter,avg_order_value_30d_recent,cancellation_rate,preferred_category,preferred_category_revenue
0,1617b1357756262bfa56ab541c47bc16,0a0a92112bd4c708ca5fde585afaa872,RJ,True,384,1,13664.08,2017-09-29,2017-07-01,13664.08,0.0,telefonia_fixa,13664.08
1,349509b216bd5ec11c5fae929fd13595,da122df9eeddfedc1dc1f5349a1a690c,RJ,True,565,2,7571.63,2017-04-01,2017-04-01,3785.82,0.0,eletroportateis,7571.63
2,df55c14d1476a9a3467f131269c2477f,da122df9eeddfedc1dc1f5349a1a690c,RJ,True,565,2,7571.63,2017-04-01,2017-04-01,3785.82,0.0,eletroportateis,7571.63
3,ec5b2ba62e574342386871631fafd3fc,763c8b1c9c68a0229c42c9fc6f662b93,ES,True,95,1,7274.88,2018-07-15,2018-07-01,7274.88,0.0,telefonia_fixa,7274.88
4,c6e2731c5b391845f6800c97401a43a9,dc4802a71eae9be1dd28f5d788ceb526,MS,True,613,1,6929.31,2017-02-12,2017-01-01,6929.31,0.0,utilidades_domesticas,6929.31
5,f48d464a0baaea338cb25f816991ab1f,459bef486812aa25204be022145caa62,ES,True,85,1,6922.21,2018-07-25,2018-07-01,6922.21,0.0,pcs,6922.21
6,3fd6777bbce08a352fddd04e4a7cc8f6,ff4159b92c40ebe40454e3e6a7c35ed6,SP,True,512,1,6726.66,2017-05-24,2017-04-01,6726.66,0.0,artes,6726.66
7,05455dfa7cd02f13d132aa7a6a9729c6,4007669dec559734d6f53e029e360987,MG,True,328,1,6081.54,2017-11-24,2017-10-01,6081.54,0.0,agro_industria_e_comercio,6081.54
8,e0a2412720e9ea4f26c1ac985f6a7358,5d0a2980b292d049061542014e8960bf,GO,True,98,1,4809.44,2018-07-12,2018-07-01,4809.44,1.0,cool_stuff,4809.44
9,24bbf5fd2f2e1b359ee7de94defc4a15,eebb5dda148d3893cdaf5b5ca3040ccb,SP,True,548,1,4764.34,2017-04-18,2017-04-01,4764.34,0.0,eletroportateis,4764.34

Кожен stage можна перевірити окремо: ті самі CTE, але замість фінального `SELECT` кількість рядків на виході кожного етапу.

In [9]:
STAGE_CTES = FEATURE_PIPELINE[:FEATURE_PIPELINE.index('\nSELECT\n    c.customer_id,')]

q(STAGE_CTES + """
SELECT 'stage1_orders_total' AS stage, COUNT(*) AS n_rows, COUNT(DISTINCT customer_unique_id) AS buyers FROM stage1_orders_total
UNION ALL SELECT 'stage2_rfm', COUNT(*), COUNT(DISTINCT customer_unique_id) FROM stage2_rfm
UNION ALL SELECT 'stage3_cohort', COUNT(*), COUNT(DISTINCT customer_unique_id) FROM stage3_cohort
UNION ALL SELECT 'stage4_rolling_aov (rn_recent = 1)', COUNT(*), COUNT(DISTINCT customer_unique_id) FROM stage4_rolling_aov WHERE rn_recent = 1
UNION ALL SELECT 'stage5_cancel_rate', COUNT(*), COUNT(DISTINCT customer_unique_id) FROM stage5_cancel_rate
UNION ALL SELECT 'stage6_category_revenue', COUNT(*), COUNT(DISTINCT customer_unique_id) FROM stage6_category_revenue
UNION ALL SELECT 'stage7_preferred_category', COUNT(*), COUNT(DISTINCT customer_unique_id) FROM stage7_preferred_category
""")

                                stage  n_rows  buyers
0                 stage1_orders_total   99441   96096
1                          stage2_rfm   96096   96096
2                       stage3_cohort   96096   96096
3  stage4_rolling_aov (rn_recent = 1)   96096   96096
4                  stage5_cancel_rate   96096   96096
5             stage6_category_revenue   97915   95420
6           stage7_preferred_category   95420   95420

Кожен stage має очікувану гранулярність. Stage 1 дає рядок на замовлення (99 441), stages 2-5 рядок на покупця (96 096). Stage 6 має 97 915 пар «покупець × категорія» для 95 420 покупців, stage 7 залишає одну категорію на покупця. Решта 676 покупців мають замовлення без жодної позиції, категорії в них немає, і фінальний `SELECT` ставить `'(none)'`.

### Що дали ознаки

Розподіли ключових ознак на рівні покупця, один рядок на `customer_unique_id`:

In [10]:
q("""
WITH buyer_features AS (
    SELECT DISTINCT ON (customer_unique_id) *
    FROM (""" + FEATURE_PIPELINE + """) AS f
    ORDER BY customer_unique_id
)
SELECT COUNT(*)                                                AS buyers,
       COUNT(*) FILTER (WHERE frequency >= 2)                  AS repeat_buyers,
       MAX(frequency)                                          AS max_frequency,
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY recency_days) AS median_recency_days,
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY monetary)  AS median_monetary,
       COUNT(*) FILTER (WHERE cancellation_rate > 0)           AS buyers_with_cancellations,
       COUNT(*) FILTER (WHERE cancellation_rate > 0 AND cancellation_rate < 1) AS buyers_partly_canceled,
       COUNT(*) FILTER (WHERE avg_order_value_30d_recent <> ROUND(monetary / NULLIF(frequency, 0), 2)) AS aov30_differs_from_mean,
       COUNT(*) FILTER (WHERE preferred_category = '(unknown)') AS preferred_category_unknown,
       COUNT(*) FILTER (WHERE NOT has_orders)                  AS buyers_without_orders
FROM buyer_features
""")

,buyers,repeat_buyers,max_frequency,median_recency_days,median_monetary,buyers_with_cancellations,buyers_partly_canceled,aov30_differs_from_mean,preferred_category_unknown,buyers_without_orders
0,96096,2997,17,270.0,107.27,616,80,1495,1375,0

In [11]:
q("""
WITH buyer_features AS (
    SELECT DISTINCT ON (customer_unique_id) *
    FROM (""" + FEATURE_PIPELINE + """) AS f
    ORDER BY customer_unique_id
)
SELECT cohort_quarter,
       COUNT(*)                                    AS buyers,
       ROUND(AVG(frequency), 3)                    AS avg_frequency,
       ROUND(AVG(monetary), 2)                     AS avg_monetary,
       ROUND(AVG(recency_days))                    AS avg_recency_days
FROM buyer_features
GROUP BY cohort_quarter
ORDER BY cohort_quarter
""")

  cohort_quarter  buyers  avg_frequency  avg_monetary  avg_recency_days
0     2016-07-01       4          1.000         88.69             769.0
1     2016-10-01     322          1.043        181.98             728.0
2     2017-01-01    5152          1.059        171.08             591.0
3     2017-04-01    9087          1.061        170.45             510.0
4     2017-07-01   12208          1.055        164.08             422.0
5     2017-10-01   17261          1.036        163.26             332.0
6     2018-01-01   20441          1.033        158.51             244.0
7     2018-04-01   19273          1.018        169.92             157.0
8     2018-07-01   12347          1.013        163.47              79.0
9     2018-10-01       1          1.000          0.00               1.0

Повторних покупців 2 997, максимум 17 замовлень. Медіанна давність останньої покупки 270 днів, медіанні витрати 107,27 BRL. Скасування мали 616 покупців, і тільки у 80 з них скасовано не все, тому `cancellation_rate` і на рівні покупця майже завжди 0 або 1. Rolling AOV відрізняється від простого середнього чека в 1 495 покупців, бо 30-денне вікно бачить тільки свіжі замовлення. Для 1 375 покупців найбільший виторг дала категорія `(unknown)`, тобто товари без категорії. Покупців без замовлень немає, тому заглушка `9999` у `recency_days` тут не трапляється.

Когортна таблиця показує пастку: середня `frequency` падає з 1,059-1,061 у когортах першого півріччя 2017 року до 1,013 у третьому кварталі 2018-го. Пізні покупці мали менше часу повернутися, і порівнювати `frequency` між когортами без поправки на тривалість спостереження некоректно.

Для порівняння те саме з гранулярністю шаблону, тобто за `customer_id`:

In [12]:
q('''
WITH per_customer_id AS (
    SELECT o.customer_id,
           COUNT(*) AS frequency,
           AVG(CASE WHEN o.order_status = 'canceled' THEN 1.0 ELSE 0.0 END) AS cancellation_rate
    FROM olist_orders AS o
    GROUP BY o.customer_id
)
SELECT COUNT(*)                                             AS customer_ids,
       COUNT(*) FILTER (WHERE frequency >= 2)               AS with_repeat_orders,
       COUNT(DISTINCT frequency)                            AS distinct_frequency_values,
       COUNT(DISTINCT cancellation_rate)                    AS distinct_cancellation_values
FROM per_customer_id
''')

   customer_ids  with_repeat_orders  distinct_frequency_values  distinct_cancellation_values
0         99441                   0                          1                             2

За `customer_id` жоден клієнт не має повторного замовлення, `frequency` має одне значення, а `cancellation_rate` два, 0 і 1. Модель отримала б не поведінку клієнта, а ознаку того, чи скасоване поточне замовлення.

## Завдання 3. Recursive CTE для referral chain

Olist не має referral-даних, тому `hw5_referrals` синтетична, як у завданні: ланцюжок перших десяти клієнтів за `customer_id`. Первинний ключ на `referred_customer_id` дає кожному клієнту не більше одного реферера, а `CHECK` забороняє запросити самого себе.

In [13]:
run_sql("""
DROP TABLE IF EXISTS hw5_referrals CASCADE;

CREATE TABLE hw5_referrals (
    referrer_customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
    referred_customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
    referred_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (referred_customer_id),
    CHECK (referrer_customer_id <> referred_customer_id)
);

WITH ordered_customers AS (
    SELECT
        customer_id,
        ROW_NUMBER() OVER (ORDER BY customer_id) AS rn
    FROM olist_customers
    ORDER BY customer_id
    LIMIT 10
)
INSERT INTO hw5_referrals (referrer_customer_id, referred_customer_id)
SELECT
    prev.customer_id AS referrer_customer_id,
    nxt.customer_id AS referred_customer_id
FROM ordered_customers AS prev
JOIN ordered_customers AS nxt
    ON nxt.rn = prev.rn + 1
ON CONFLICT (referred_customer_id) DO NOTHING;
""")

In [14]:
q('''
SELECT referrer_customer_id, referred_customer_id
FROM hw5_referrals
ORDER BY referrer_customer_id, referred_customer_id
''')

               referrer_customer_id              referred_customer_id
0  00012a2ce6f8dcda20d059ce98491703  000161a058600d5901f007fab4c27140
1  000161a058600d5901f007fab4c27140  0001fd6190edaaf884bcaf3d49edf079
2  0001fd6190edaaf884bcaf3d49edf079  0002414f95344307404f0ace7a26f1d5
3  0002414f95344307404f0ace7a26f1d5  000379cdec625522490c315e70c7a9fb
4  000379cdec625522490c315e70c7a9fb  0004164d20a9e969af783496f3408652
5  0004164d20a9e969af783496f3408652  000419c5494106c306a97b5635748086
6  000419c5494106c306a97b5635748086  00046a560d407e99b969756e0b10f282
7  00046a560d407e99b969756e0b10f282  00050bf6e01e69d5c0fd612f1bcfb69c
8  00050bf6e01e69d5c0fd612f1bcfb69c  000598caf2ef4117407665ac33275130

Anchor бере корені, яких ніхто не запросив, через `NOT EXISTS`: `NOT IN` з `NULL` у підзапиті повернув би порожній результат. Recursive part переходить від реферера до запрошених і накопичує `depth`, масив `path_ids` і текстовий `path_text`. Захистів два: `NOT r.referred_customer_id = ANY(rd.path_ids)` не пускає у вже відвіданий вузол, а `rd.depth < 50` обмежує глибину навіть за помилки в першій умові.

In [15]:
q('''
WITH RECURSIVE referral_depth AS (
    -- ANCHOR: root customers that nobody referred
    SELECT
        c.customer_id,
        1 AS depth,
        ARRAY[c.customer_id]::TEXT[] AS path_ids,
        c.customer_id::TEXT AS path_text
    FROM olist_customers AS c
    WHERE NOT EXISTS (
        SELECT 1
        FROM hw5_referrals AS r
        WHERE r.referred_customer_id = c.customer_id
    )

    UNION ALL

    -- RECURSIVE: from a referrer to the customers it referred
    SELECT
        r.referred_customer_id AS customer_id,
        rd.depth + 1 AS depth,
        rd.path_ids || r.referred_customer_id AS path_ids,
        rd.path_text || ' -> ' || r.referred_customer_id AS path_text
    FROM hw5_referrals AS r
    JOIN referral_depth AS rd
        ON rd.customer_id = r.referrer_customer_id
    WHERE NOT r.referred_customer_id = ANY(rd.path_ids)
      AND rd.depth < 50
)
SELECT
    depth,
    COUNT(*) AS n_customers,
    LEFT(MAX(path_text), 70) || CASE WHEN LENGTH(MAX(path_text)) > 70 THEN '...' ELSE '' END AS sample_path
FROM referral_depth
GROUP BY depth
ORDER BY depth
''')

   depth  n_customers                                                                sample_path
0      1        99432                                           ffffe8b65bbe3087b653a978c870db99
1      2            1       00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140
2      3            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -...
3      4            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -...
4      5            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -...
5      6            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -...
6      7            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -...
7      8            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -...
8      9            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -...
9     10            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -...

Коренів 99 432: усі клієнти, крім дев'яти запрошених. Далі ланцюжок іде по одному клієнту на рівень до глибини 10, і `path_text` містить шлях від першого клієнта. Рекурсія зупиняється сама, коли recursive part більше не повертає рядків: в останнього в ланцюжку немає запрошених.

### Граф із циклом

Щоб побачити захисти в дії, запускаю той самий обхід на маленькому графі: `A` запрошує `B`, `B` запрошує `C`, а `C` знову `A`. Граф задано через `VALUES`, обхід починається з `A`. Спершу з обома захистами:

In [16]:
q('''
WITH RECURSIVE edges (referrer, referred) AS (
    VALUES ('A', 'B'), ('B', 'C'), ('C', 'A')
),
walk AS (
    SELECT 'A'::TEXT AS customer_id, 1 AS depth, ARRAY['A']::TEXT[] AS path_ids
    UNION ALL
    SELECT e.referred, w.depth + 1, w.path_ids || e.referred
    FROM edges AS e
    JOIN walk AS w
        ON w.customer_id = e.referrer
    WHERE NOT e.referred = ANY(w.path_ids)
      AND w.depth < 50
)
SELECT depth, customer_id, ARRAY_TO_STRING(path_ids, ' -> ') AS path
FROM walk
ORDER BY depth
''')

   depth customer_id         path
0      1           A            A
1      2           B       A -> B
2      3           C  A -> B -> C

Тепер без перевірки `path_ids`, лише з обмеженням глибини:

In [17]:
q('''
WITH RECURSIVE edges (referrer, referred) AS (
    VALUES ('A', 'B'), ('B', 'C'), ('C', 'A')
),
walk AS (
    SELECT 'A'::TEXT AS customer_id, 1 AS depth, ARRAY['A']::TEXT[] AS path_ids
    UNION ALL
    SELECT e.referred, w.depth + 1, w.path_ids || e.referred
    FROM edges AS e
    JOIN walk AS w
        ON w.customer_id = e.referrer
    WHERE w.depth < 50
)
SELECT COUNT(*)                         AS rows_produced,
       MAX(depth)                       AS max_depth,
       COUNT(DISTINCT customer_id)      AS distinct_customers,
       MAX(CARDINALITY(path_ids))       AS longest_path
FROM walk
''')

   rows_produced  max_depth  distinct_customers  longest_path
0             50         50                   3            50

І вбудований механізм PostgreSQL 14+: `CYCLE customer_id SET is_cycle USING cycle_path` сам веде шлях і позначає рядок, на якому вузол повторився:

In [18]:
q('''
WITH RECURSIVE edges (referrer, referred) AS (
    VALUES ('A', 'B'), ('B', 'C'), ('C', 'A')
),
walk (customer_id, depth) AS (
    SELECT 'A'::TEXT, 1
    UNION ALL
    SELECT e.referred, w.depth + 1
    FROM edges AS e
    JOIN walk AS w
        ON w.customer_id = e.referrer
) CYCLE customer_id SET is_cycle USING cycle_path
SELECT depth, customer_id, is_cycle, cycle_path::TEXT AS cycle_path
FROM walk
ORDER BY depth
''')

   depth customer_id  is_cycle         cycle_path
0      1           A     False              {(A)}
1      2           B     False          {(A),(B)}
2      3           C     False      {(A),(B),(C)}
3      4           A      True  {(A),(B),(C),(A)}

З обома захистами обхід зупинився на `C`, бо наступний крок вів би до `A`, який уже є в `path_ids`. Без перевірки шляху обхід дав 50 рядків по колу з трьох клієнтів, і зупинило його тільки обмеження глибини, а без нього запит не завершився б. `CYCLE` робить те саме декларативно: рядок, де `A` трапився вдруге, має `is_cycle = true`, і далі рекурсія не йде.

У `hw5_referrals` первинний ключ на `referred_customer_id` дає кожному клієнту не більше одного реферера. Тому замкнений цикл не має кореня, і обхід від коренів його не побачить: такі клієнти випадуть з результату. Захисти потрібні, коли обхід стартує з довільного клієнта або граф дозволяє кількох реферерів.

## Завдання 4. Materialized View з concurrent refresh

MV будується з повного `FEATURE_PIPELINE`.

In [19]:
run_sql("""
DROP MATERIALIZED VIEW IF EXISTS mv_olist_customer_features CASCADE;

CREATE MATERIALIZED VIEW mv_olist_customer_features AS
""" + FEATURE_PIPELINE)

q("SELECT COUNT(*) AS n_rows FROM mv_olist_customer_features")

   n_rows
0   99441

Спершу перевірка, навіщо потрібен унікальний індекс: без нього concurrent refresh неможливий.

In [20]:
try:
    run_sql("REFRESH MATERIALIZED VIEW CONCURRENTLY mv_olist_customer_features")
except DBAPIError as err:
    print('очікувана помилка:', str(err.orig).strip())

очікувана помилка: cannot refresh materialized view "public.mv_olist_customer_features" concurrently
HINT:  Create a unique index with no WHERE clause on one or more columns of the materialized view.

In [21]:
run_sql("""
CREATE UNIQUE INDEX idx_mv_olist_customer_features_customer_id
    ON mv_olist_customer_features (customer_id);
""")

In [22]:
q('''
SELECT *
FROM mv_olist_customer_features
ORDER BY monetary DESC NULLS LAST, customer_id
LIMIT 5
''')

,customer_id,customer_unique_id,customer_state,has_orders,recency_days,frequency,monetary,first_order_date,cohort_quarter,avg_order_value_30d_recent,cancellation_rate,preferred_category,preferred_category_revenue
0,1617b1357756262bfa56ab541c47bc16,0a0a92112bd4c708ca5fde585afaa872,RJ,True,384,1,13664.08,2017-09-29,2017-07-01,13664.08,0.0,telefonia_fixa,13664.08
1,349509b216bd5ec11c5fae929fd13595,da122df9eeddfedc1dc1f5349a1a690c,RJ,True,565,2,7571.63,2017-04-01,2017-04-01,3785.82,0.0,eletroportateis,7571.63
2,df55c14d1476a9a3467f131269c2477f,da122df9eeddfedc1dc1f5349a1a690c,RJ,True,565,2,7571.63,2017-04-01,2017-04-01,3785.82,0.0,eletroportateis,7571.63
3,ec5b2ba62e574342386871631fafd3fc,763c8b1c9c68a0229c42c9fc6f662b93,ES,True,95,1,7274.88,2018-07-15,2018-07-01,7274.88,0.0,telefonia_fixa,7274.88
4,c6e2731c5b391845f6800c97401a43a9,dc4802a71eae9be1dd28f5d788ceb526,MS,True,613,1,6929.31,2017-02-12,2017-01-01,6929.31,0.0,utilidades_domesticas,6929.31

Concurrent refresh окремою клітинкою, після створення індексу:

In [23]:
run_sql("REFRESH MATERIALIZED VIEW CONCURRENTLY mv_olist_customer_features")
q("""
SELECT COUNT(*)                                                              AS n_rows,
       COUNT(DISTINCT customer_id)                                           AS distinct_customer_ids,
       pg_size_pretty(pg_relation_size('mv_olist_customer_features'))        AS mv_size,
       pg_size_pretty(pg_indexes_size('mv_olist_customer_features'))         AS indexes_size
FROM mv_olist_customer_features
""")

   n_rows  distinct_customer_ids mv_size indexes_size
0   99441                  99441   17 MB      5760 kB

MV має 99 441 рядок, по одному на `customer_id`. Перша спроба concurrent refresh упала з підказкою створити унікальний індекс без `WHERE`: `CONCURRENTLY` будує новий результат поруч зі старим і переносить різницю рядок за рядком, а для цього потрібен унікальний ключ. Після `CREATE UNIQUE INDEX` refresh пройшов. На відміну від звичайного `REFRESH`, він не блокує читання, і поки рахується новий результат, запити бачать попередній. MV займає 17 МБ, унікальний індекс ще 5760 кБ.

### MV показує стан на момент останнього refresh

Беру покупця з найбільшою кількістю замовлень, тимчасово змінюю статус одного його замовлення на `canceled` і порівнюю MV з живим pipeline до і після refresh. Наприкінці зміна відкочується, і MV оновлюється знову.

In [24]:
probe = q("""
SELECT customer_id, customer_unique_id, frequency, cancellation_rate
FROM mv_olist_customer_features
ORDER BY frequency DESC, customer_unique_id, customer_id
LIMIT 1
""").iloc[0]

probe_order = q("""
SELECT o.order_id, o.order_status
FROM olist_orders AS o
JOIN olist_customers AS c ON c.customer_id = o.customer_id
WHERE c.customer_unique_id = :uid AND o.order_status <> 'canceled'
ORDER BY o.order_purchase_timestamp DESC, o.order_id
LIMIT 1
""", uid=probe.customer_unique_id).iloc[0]


def freshness_snapshot(label: str) -> dict:
    mv_rate = q("SELECT cancellation_rate FROM mv_olist_customer_features WHERE customer_id = :cid",
                cid=probe.customer_id).iat[0, 0]
    live_rate = q("SELECT cancellation_rate FROM (" + FEATURE_PIPELINE + ") AS f WHERE f.customer_id = :cid",
                  cid=probe.customer_id).iat[0, 0]
    return {'крок': label, 'MV': mv_rate, 'живий pipeline': live_rate}


snapshots = [freshness_snapshot('вихідний стан')]
run_sql("UPDATE olist_orders SET order_status = 'canceled' WHERE order_id = :oid", oid=probe_order.order_id)
snapshots.append(freshness_snapshot('після UPDATE, до refresh'))
run_sql("REFRESH MATERIALIZED VIEW CONCURRENTLY mv_olist_customer_features")
snapshots.append(freshness_snapshot('після REFRESH CONCURRENTLY'))
run_sql("UPDATE olist_orders SET order_status = :status WHERE order_id = :oid",
        status=probe_order.order_status, oid=probe_order.order_id)
run_sql("REFRESH MATERIALIZED VIEW CONCURRENTLY mv_olist_customer_features")
snapshots.append(freshness_snapshot('після відкату і refresh'))

print(f"покупець {probe.customer_unique_id}: {probe.frequency} замовлень")
pd.DataFrame(snapshots)

покупець 8d50f5eadf50201ccdcedfb9e2ac8455: 17 замовлень

                         крок      MV  живий pipeline
0               вихідний стан  0.0000          0.0000
1    після UPDATE, до refresh  0.0000          0.0588
2  після REFRESH CONCURRENTLY  0.0588          0.0588
3     після відкату і refresh  0.0000          0.0000

Покупець із 17 замовленнями мав `cancellation_rate = 0`. Після `UPDATE` живий pipeline одразу показав 0,0588, тобто 1 з 17, а MV і далі віддавала 0, бо зберігає результат останнього refresh. Нове значення з'явилося в MV тільки після `REFRESH ... CONCURRENTLY`. Після відкату й ще одного refresh обидва значення повернулися до 0.

## Завдання 5. `EXPLAIN (ANALYZE, BUFFERS)`

### 5.1. Повне переобчислення RFM-частини pipeline (stages 0-2)

In [25]:
RFM_QUERY = """
WITH
reference_date AS (
    SELECT (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    SELECT
        c.customer_unique_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp AS order_ts,
        o.order_purchase_timestamp::DATE AS order_date,
        COALESCE(SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        ), 0)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    JOIN olist_customers AS c
        ON c.customer_id = o.customer_id
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        c.customer_unique_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp
),
stage2_rfm AS (
    SELECT
        s.customer_unique_id,
        (rd.as_of_date - MAX(s.order_date))::INTEGER AS recency_days,
        COUNT(*) AS frequency,
        SUM(s.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(s.order_date) AS first_order_date
    FROM stage1_orders_total AS s
    CROSS JOIN reference_date AS rd
    GROUP BY s.customer_unique_id, rd.as_of_date
)
SELECT *
FROM stage2_rfm
ORDER BY monetary DESC NULLS LAST
LIMIT 10
"""

rfm_plan = explain(RFM_QUERY)
print('\n'.join(rfm_plan))

Limit  (cost=37938.93..37938.95 rows=10 width=65) (actual time=324.426..325.621 rows=10 loops=1)
  Buffers: shared hit=7418, temp read=2429 written=3166
  ->  Sort  (cost=37938.93..37939.43 rows=200 width=65) (actual time=324.425..325.619 rows=10 loops=1)
        Sort Key: stage2_rfm.monetary DESC NULLS LAST
        Sort Method: top-N heapsort  Memory: 27kB
        Buffers: shared hit=7418, temp read=2429 written=3166
        ->  Subquery Scan on stage2_rfm  (cost=37929.11..37934.61 rows=200 width=65) (actual time=255.107..314.296 rows=96096 loops=1)
              Buffers: shared hit=7418, temp read=2429 written=3166
              ->  HashAggregate  (cost=37929.11..37932.61 rows=200 width=69) (actual time=255.105..306.849 rows=96096 loops=1)
                    Group Key: c.customer_unique_id, (((max(olist_orders.order_purchase_timestamp))::date + 1))
                    Batches: 21  Memory Usage: 8265kB  Disk Usage: 7376kB
                    Buffers: shared hit=7418, temp read=2429 written=3166
                    ->  Nested Loop  (cost=21959.25..36239.36 rows=112650 width=57) (actual time=110.405..223.337 rows=99441 loops=1)
                          Buffers: shared hit=7418, temp read=1545 written=1549
                          ->  Finalize GroupAggregate  (cost=18906.55..30652.01 rows=112650 width=103) (actual time=99.398..190.675 rows=99441 loops=1)
                                Group Key: c.customer_unique_id, o.order_id
                                Buffers: shared hit=5609, temp read=1545 written=1549
                                ->  Gather Merge  (cost=18906.55..28017.99 rows=66265 width=115) (actual time=99.387..144.244 rows=99662 loops=1)
                                      Workers Planned: 1
                                      Workers Launched: 1
                                      Buffers: shared hit=5609, temp read=1545 written=1549
                                      ->  Partial GroupAggregate  (cost=17906.54..19563.17 rows=66265 width=115) (actual time=94.689..133.932 rows=49831 loops=2)
                                            Group Key: c.customer_unique_id, o.order_id
                                            Buffers: shared hit=5609, temp read=1545 written=1549
                                            ->  Sort  (cost=17906.54..18072.20 rows=66265 width=95) (actual time=94.667..102.555 rows=56712 loops=2)
                                                  Sort Key: c.customer_unique_id, o.order_id
                                                  Sort Method: external merge  Disk: 6368kB
                                                  Buffers: shared hit=5609, temp read=1545 written=1549
                                                  Worker 0:  Sort Method: external merge  Disk: 5992kB
                                                  ->  Parallel Hash Join  (cost=5891.99..9201.55 rows=66265 width=95) (actual time=24.872..75.115 rows=56712 loops=2)
                                                        Hash Cond: (o.customer_id = c.customer_id)
                                                        Buffers: shared hit=5572
                                                        ->  Parallel Hash Right Join  (cost=3125.86..6261.46 rows=66265 width=95) (actual time=13.827..42.688 rows=56712 loops=2)
                                                              Hash Cond: (oi.order_id = o.order_id)
                                                              Buffers: shared hit=4108
                                                              ->  Parallel Seq Scan on olist_order_items oi  (cost=0.00..2961.65 rows=66265 width=45) (actual time=0.006..5.948 rows=56325 loops=2)
                                                                    Buffers: shared hit=2299
                                                              ->  Parallel Hash  (cost=2394.27..2394.27 rows=58527 width=83) (actual time=13.653..13.656 rows=49720 loops=2)
                                                                    Buckets: 131072  Batches: 1  Memory Usage: 13536kB
                                                                    Buffers: shared hit=1809
                                                                    ->  Parallel Seq Scan on olist_orders o  (cost=0.00..2394.27 rows=58527 width=83) (actual time=0.008..5.663 rows=49720 loops=2)
                                                                          Buffers: shared hit=1809
                                                        ->  Parallel Hash  (cost=2034.95..2034.95 rows=58495 width=66) (actual time=10.859..10.859 rows=49720 loops=2)
                                                              Buckets: 131072  Batches: 1  Memory Usage: 11200kB
                                                              Buffers: shared hit=1450
                                                              ->  Parallel Seq Scan on olist_customers c  (cost=0.00..2034.95 rows=58495 width=66) (actual time=0.008..4.340 rows=49720 loops=2)
                                                                    Buffers: shared hit=1450
                          ->  Materialize  (cost=3052.70..3052.72 rows=1 width=4) (actual time=0.000..0.000 rows=1 loops=99441)
                                Buffers: shared hit=1809
                                ->  Aggregate  (cost=3052.70..3052.72 rows=1 width=4) (actual time=10.998..10.998 rows=1 loops=1)
                                      Buffers: shared hit=1809
                                      ->  Seq Scan on olist_orders  (cost=0.00..2803.96 rows=99496 width=8) (actual time=0.010..6.180 rows=99441 loops=1)
                                            Buffers: shared hit=1809
Planning:
  Buffers: shared hit=26
Planning Time: 0.866 ms
Execution Time: 328.482 ms

### 5.2. Повний pipeline з усіма ознаками

In [26]:
full_plan = explain(FEATURE_PIPELINE)
print('\n'.join(full_plan))

Merge Left Join  (cost=78927.11..126256.59 rows=99441 width=184) (actual time=965.378..1611.461 rows=99441 loops=1)
  Merge Cond: (c.customer_unique_id = ranked.customer_unique_id)
  Buffers: shared hit=114193, temp read=10418 written=10488
  CTE stage1_orders_total
    ->  Finalize GroupAggregate  (cost=18906.55..30652.01 rows=112650 width=103) (actual time=177.321..353.088 rows=99441 loops=1)
          Group Key: c_2.customer_unique_id, o_1.order_id
          Buffers: shared hit=5609, temp read=1545 written=1549
          ->  Gather Merge  (cost=18906.55..28017.99 rows=66265 width=115) (actual time=177.296..260.276 rows=99650 loops=1)
                Workers Planned: 1
                Workers Launched: 1
                Buffers: shared hit=5609, temp read=1545 written=1549
                ->  Partial GroupAggregate  (cost=17906.54..19563.17 rows=66265 width=115) (actual time=169.180..238.191 rows=49825 loops=2)
                      Group Key: c_2.customer_unique_id, o_1.order_id
                      Buffers: shared hit=5609, temp read=1545 written=1549
                      ->  Sort  (cost=17906.54..18072.20 rows=66265 width=95) (actual time=169.131..183.535 rows=56712 loops=2)
                            Sort Key: c_2.customer_unique_id, o_1.order_id
                            Sort Method: external merge  Disk: 6272kB
                            Buffers: shared hit=5609, temp read=1545 written=1549
                            Worker 0:  Sort Method: external merge  Disk: 6088kB
                            ->  Parallel Hash Join  (cost=5891.99..9201.55 rows=66265 width=95) (actual time=24.427..124.326 rows=56712 loops=2)
                                  Hash Cond: (o_1.customer_id = c_2.customer_id)
                                  Buffers: shared hit=5572
                                  ->  Parallel Hash Right Join  (cost=3125.86..6261.46 rows=66265 width=95) (actual time=12.493..71.002 rows=56712 loops=2)
                                        Hash Cond: (oi_1.order_id = o_1.order_id)
                                        Buffers: shared hit=4108
                                        ->  Parallel Seq Scan on olist_order_items oi_1  (cost=0.00..2961.65 rows=66265 width=45) (actual time=0.007..14.073 rows=56325 loops=2)
                                              Buffers: shared hit=2299
                                        ->  Parallel Hash  (cost=2394.27..2394.27 rows=58527 width=83) (actual time=12.353..12.356 rows=49720 loops=2)
                                              Buckets: 131072  Batches: 1  Memory Usage: 13536kB
                                              Buffers: shared hit=1809
                                              ->  Parallel Seq Scan on olist_orders o_1  (cost=0.00..2394.27 rows=58527 width=83) (actual time=0.007..5.041 rows=49720 loops=2)
                                                    Buffers: shared hit=1809
                                  ->  Parallel Hash  (cost=2034.95..2034.95 rows=58495 width=66) (actual time=11.749..11.749 rows=49720 loops=2)
                                        Buckets: 131072  Batches: 1  Memory Usage: 11200kB
                                        Buffers: shared hit=1450
                                        ->  Parallel Seq Scan on olist_customers c_2  (cost=0.00..2034.95 rows=58495 width=66) (actual time=0.006..4.945 rows=49720 loops=2)
                                              Buffers: shared hit=1450
  ->  Merge Left Join  (cost=28384.63..52861.37 rows=99441 width=167) (actual time=827.625..1223.196 rows=99441 loops=1)
        Merge Cond: (c.customer_unique_id = cancel.customer_unique_id)
        Buffers: shared hit=105238, temp read=8660 written=8726
        ->  Merge Left Join  (cost=25274.11..49499.13 rows=99441 width=153) (actual time=718.446..1075.719 rows=99441 loops=1)
              Merge Cond: (c.customer_unique_id = aov.customer_unique_id)
              Buffers: shared hit=105238, temp read=6095 written=6747
              ->  Merge Left Join  (cost=8137.03..19388.29 rows=99441 width=137) (actual time=669.933..802.750 rows=99441 loops=1)
                    Merge Cond: (c.customer_unique_id = r.customer_unique_id)
                    Buffers: shared hit=105238, temp read=3591 written=5562
                    ->  Index Scan using idx_olist_customers_unique_id on olist_customers c  (cost=0.42..10999.91 rows=99441 width=69) (actual time=0.011..77.663 rows=99441 loops=1)
                          Buffers: shared hit=100292
                    ->  Sort  (cost=8136.61..8137.11 rows=200 width=68) (actual time=669.902..686.223 rows=99441 loops=1)
                          Sort Key: r.customer_unique_id
                          Sort Method: external sort  Disk: 7344kB
                          Buffers: shared hit=4946, temp read=3547 written=5562
                          ->  Subquery Scan on r  (cost=8121.97..8128.97 rows=200 width=68) (actual time=509.203..616.205 rows=96096 loops=1)
                                Buffers: shared hit=4946, temp read=1668 written=3725
                                ->  HashAggregate  (cost=8121.97..8125.47 rows=200 width=68) (actual time=509.193..587.172 rows=96096 loops=1)
                                      Group Key: s.customer_unique_id, (((max(olist_orders.order_purchase_timestamp))::date + 1))
                                      Batches: 21  Memory Usage: 8265kB  Disk Usage: 7376kB
                                      Buffers: shared hit=4946, temp read=1668 written=3725
                                      ->  Nested Loop  (cost=3052.70..6432.22 rows=112650 width=56) (actual time=187.862..442.261 rows=99441 loops=1)
                                            Buffers: shared hit=4946, temp read=784 written=2108
                                            ->  Aggregate  (cost=3052.70..3052.72 rows=1 width=4) (actual time=10.536..10.536 rows=1 loops=1)
                                                  Buffers: shared hit=1809
                                                  ->  Seq Scan on olist_orders  (cost=0.00..2803.96 rows=99496 width=8) (actual time=0.003..5.864 rows=99441 loops=1)
                                                        Buffers: shared hit=1809
                                            ->  CTE Scan on stage1_orders_total s  (cost=0.00..2253.00 rows=112650 width=52) (actual time=177.323..415.616 rows=99441 loops=1)
                                                  Buffers: shared hit=3137, temp read=784 written=2108
              ->  Materialize  (cost=17137.08..29854.73 rows=563 width=48) (actual time=48.506..242.811 rows=99441 loops=1)
                    Buffers: temp read=2504 written=1185
                    ->  Subquery Scan on aov  (cost=17137.08..29853.32 rows=563 width=48) (actual time=48.501..222.308 rows=96096 loops=1)
                          Filter: (aov.rn_recent = 1)
                          Buffers: temp read=2504 written=1185
                          ->  WindowAgg  (cost=17137.08..28445.19 rows=112650 width=112) (actual time=48.499..214.794 rows=96096 loops=1)
                                Filter: ((row_number() OVER (?)) <= 1)
                                Rows Removed by Filter: 3345
                                Buffers: temp read=2504 written=1185
                                ->  Incremental Sort  (cost=17137.08..26192.19 rows=112650 width=96) (actual time=48.480..119.154 rows=99441 loops=1)
                                      Sort Key: s_1.customer_unique_id, s_1.order_ts
                                      Presorted Key: s_1.customer_unique_id
                                      Full-sort Groups: 3104  Sort Method: quicksort  Average Memory: 28kB  Peak Memory: 28kB
                                      Buffers: temp read=2504 written=1185
                                      ->  WindowAgg  (cost=17098.67..19633.30 rows=112650 width=96) (actual time=48.419..93.505 rows=99441 loops=1)
                                            Run Condition: (row_number() OVER (?) <= 1)
                                            Buffers: temp read=2504 written=1185
                                            ->  Sort  (cost=17098.67..17380.30 rows=112650 width=88) (actual time=48.404..59.838 rows=99441 loops=1)
                                                  Sort Key: s_1.customer_unique_id, s_1.order_ts DESC, s_1.order_id DESC
                                                  Sort Method: external merge  Disk: 9448kB
                                                  Buffers: temp read=2504 written=1185
                                                  ->  CTE Scan on stage1_orders_total s_1  (cost=0.00..2253.00 rows=112650 width=88) (actual time=0.054..18.197 rows=99441 loops=1)
                                                        Buffers: temp read=1323 written=1
        ->  Sort  (cost=3110.52..3111.02 rows=200 width=46) (actual time=109.173..121.180 rows=96096 loops=1)
              Sort Key: cancel.customer_unique_id
              Sort Method: external merge  Disk: 4344kB
              Buffers: temp read=2565 written=1979
              ->  Subquery Scan on cancel  (cost=3097.88..3102.88 rows=200 width=46) (actual time=36.061..88.731 rows=96096 loops=1)
                    Buffers: temp read=2022 written=1434
                    ->  HashAggregate  (cost=3097.88..3100.88 rows=200 width=46) (actual time=36.060..82.350 rows=96096 loops=1)
                          Group Key: stage1_orders_total.customer_unique_id
                          Batches: 21  Memory Usage: 8265kB  Disk Usage: 7168kB
                          Buffers: temp read=2022 written=1434
                          ->  CTE Scan on stage1_orders_total  (cost=0.00..2253.00 rows=112650 width=64) (actual time=0.010..8.706 rows=99441 loops=1)
                                Buffers: temp read=1323
  ->  Materialize  (cost=19890.47..41492.68 rows=563 width=81) (actual time=137.744..336.759 rows=98756 loops=1)
        Buffers: shared hit=6483, temp read=997 written=999
        ->  Subquery Scan on ranked  (cost=19890.47..41491.27 rows=563 width=81) (actual time=137.742..315.709 rows=95420 loops=1)
              Filter: (ranked.rn = 1)
              Buffers: shared hit=6483, temp read=997 written=999
              ->  WindowAgg  (cost=19890.47..40083.15 rows=112650 width=121) (actual time=137.741..308.211 rows=95420 loops=1)
                    Run Condition: (row_number() OVER (?) <= 1)
                    Buffers: shared hit=6483, temp read=997 written=999
                    ->  Incremental Sort  (cost=19890.47..37830.15 rows=112650 width=113) (actual time=137.733..269.550 rows=97915 loops=1)
                          Sort Key: cr.customer_unique_id, cr.category_revenue DESC, ((cr.product_category_name)::text) COLLATE "C"
                          Presorted Key: cr.customer_unique_id
                          Full-sort Groups: 3058  Sort Method: quicksort  Average Memory: 28kB  Peak Memory: 28kB
                          Buffers: shared hit=6483, temp read=997 written=999
                          ->  Subquery Scan on cr  (cost=19807.42..31271.25 rows=112650 width=113) (actual time=137.608..247.827 rows=97915 loops=1)
                                Buffers: shared hit=6483, temp read=997 written=999
                                ->  Finalize GroupAggregate  (cost=19807.42..31271.25 rows=112650 width=81) (actual time=137.607..238.311 rows=97915 loops=1)
                                      Group Key: c_1.customer_unique_id, (COALESCE(p.product_category_name, '(unknown)'::text))
                                      Buffers: shared hit=6483, temp read=997 written=999
                                      ->  Gather Merge  (cost=19807.42..28918.85 rows=66265 width=97) (actual time=137.598..188.409 rows=98854 loops=1)
                                            Workers Planned: 1
                                            Workers Launched: 1
                                            Buffers: shared hit=6483, temp read=997 written=999
                                            ->  Partial GroupAggregate  (cost=18807.41..20464.03 rows=66265 width=97) (actual time=133.276..177.431 rows=49427 loops=2)
                                                  Group Key: c_1.customer_unique_id, (COALESCE(p.product_category_name, '(unknown)'::text))
                                                  Buffers: shared hit=6483, temp read=997 written=999
                                                  ->  Sort  (cost=18807.41..18973.07 rows=66265 width=77) (actual time=133.252..141.211 rows=56325 loops=2)
                                                        Sort Key: c_1.customer_unique_id, (COALESCE(p.product_category_name, '(unknown)'::text))
                                                        Sort Method: external merge  Disk: 4232kB
                                                        Buffers: shared hit=6483, temp read=997 written=999
                                                        Worker 0:  Sort Method: external merge  Disk: 3744kB
                                                        ->  Hash Left Join  (cost=7070.39..10553.92 rows=66265 width=77) (actual time=32.088..111.649 rows=56325 loops=2)
                                                              Hash Cond: (oi.product_id = p.product_id)
                                                              Buffers: shared hit=6446
                                                              ->  Parallel Hash Join  (cost=5891.99..9201.55 rows=66265 width=78) (actual time=23.777..83.340 rows=56325 loops=2)
                                                                    Hash Cond: (o.customer_id = c_1.customer_id)
                                                                    Buffers: shared hit=5572
                                                                    ->  Parallel Hash Join  (cost=3125.86..6261.46 rows=66265 width=78) (actual time=12.131..46.727 rows=56325 loops=2)
                                                                          Hash Cond: (oi.order_id = o.order_id)
                                                                          Buffers: shared hit=4108
                                                                          ->  Parallel Seq Scan on olist_order_items oi  (cost=0.00..2961.65 rows=66265 width=78) (actual time=0.006..7.734 rows=56325 loops=2)
                                                                                Buffers: shared hit=2299
                                                                          ->  Parallel Hash  (cost=2394.27..2394.27 rows=58527 width=66) (actual time=11.990..11.991 rows=49720 loops=2)
                                                                                Buckets: 131072  Batches: 1  Memory Usage: 11168kB
                                                                                Buffers: shared hit=1809
                                                                                ->  Parallel Seq Scan on olist_orders o  (cost=0.00..2394.27 rows=58527 width=66) (actual time=0.006..5.052 rows=49720 loops=2)
                                                                                      Buffers: shared hit=1809
                                                                    ->  Parallel Hash  (cost=2034.95..2034.95 rows=58495 width=66) (actual time=11.457..11.458 rows=49720 loops=2)
                                                                          Buckets: 131072  Batches: 1  Memory Usage: 11168kB
                                                                          Buffers: shared hit=1450
                                                                          ->  Parallel Seq Scan on olist_customers c_1  (cost=0.00..2034.95 rows=58495 width=66) (actual time=0.008..4.464 rows=49720 loops=2)
                                                                                Buffers: shared hit=1450
                                                              ->  Hash  (cost=766.51..766.51 rows=32951 width=48) (actual time=8.238..8.238 rows=32951 loops=2)
                                                                    Buckets: 65536  Batches: 1  Memory Usage: 3108kB
                                                                    Buffers: shared hit=874
                                                                    ->  Seq Scan on olist_products p  (cost=0.00..766.51 rows=32951 width=48) (actual time=0.040..3.452 rows=32951 loops=2)
                                                                          Buffers: shared hit=874
Planning:
  Buffers: shared hit=58
Planning Time: 0.718 ms
Execution Time: 1624.201 ms

### 5.3. Lookup з MV за `customer_id`

In [27]:
MV_LOOKUP = """
WITH target_customer AS (
    SELECT customer_id
    FROM olist_customers
    ORDER BY customer_id
    LIMIT 1
)
SELECT mv.*
FROM mv_olist_customer_features AS mv
JOIN target_customer AS t
    ON t.customer_id = mv.customer_id
"""

lookup_plan = explain(MV_LOOKUP)
print('\n'.join(lookup_plan))

Nested Loop  (cost=0.83..8.96 rows=1 width=191) (actual time=0.046..0.047 rows=1 loops=1)
  Buffers: shared hit=8
  ->  Limit  (cost=0.42..0.53 rows=1 width=33) (actual time=0.026..0.027 rows=1 loops=1)
        Buffers: shared hit=4
        ->  Index Only Scan using olist_customers_pkey on olist_customers  (cost=0.42..11127.88 rows=99441 width=33) (actual time=0.014..0.014 rows=1 loops=1)
              Heap Fetches: 1
              Buffers: shared hit=4
  ->  Index Scan using idx_mv_olist_customer_features_customer_id on mv_olist_customer_features mv  (cost=0.42..8.44 rows=1 width=191) (actual time=0.017..0.017 rows=1 loops=1)
        Index Cond: (customer_id = olist_customers.customer_id)
        Buffers: shared hit=4
Planning Time: 0.149 ms
Execution Time: 0.065 ms

### 5.4. Top-N з MV з окремим індексом на `monetary`

In [28]:
run_sql("""
CREATE INDEX IF NOT EXISTS idx_mv_olist_customer_features_monetary
    ON mv_olist_customer_features (monetary DESC);
ANALYZE mv_olist_customer_features;
""")

MV_TOP_N = """
SELECT *
FROM mv_olist_customer_features
ORDER BY monetary DESC NULLS LAST
LIMIT 10
"""

top_plan = explain(MV_TOP_N)
print('\n'.join(top_plan))

Limit  (cost=4961.01..4962.16 rows=10 width=126) (actual time=10.903..11.987 rows=10 loops=1)
  Buffers: shared hit=2148
  ->  Gather Merge  (cost=4961.01..11687.94 rows=58495 width=126) (actual time=10.901..11.981 rows=10 loops=1)
        Workers Planned: 1
        Workers Launched: 1
        Buffers: shared hit=2148
        ->  Sort  (cost=3961.00..4107.24 rows=58495 width=126) (actual time=8.133..8.151 rows=10 loops=2)
              Sort Key: monetary DESC NULLS LAST
              Sort Method: top-N heapsort  Memory: 29kB
              Buffers: shared hit=2148
              Worker 0:  Sort Method: top-N heapsort  Memory: 30kB
              ->  Parallel Seq Scan on mv_olist_customer_features  (cost=0.00..2696.95 rows=58495 width=126) (actual time=0.006..3.578 rows=49720 loops=2)
                    Buffers: shared hit=2112
Planning:
  Buffers: shared hit=58 read=1
Planning Time: 0.223 ms
Execution Time: 12.020 ms

Індекс із шаблону тут не працює: у плані `Parallel Seq Scan` по всій MV і `Sort` з `top-N heapsort`, 12 мс. Індекс `(monetary DESC)` зберігає `NULL` першими, бо для `DESC` це типовий порядок, а запит просить `DESC NULLS LAST`. Для планувальника це різні порядки, навіть коли `NULL` у колонці немає.

In [29]:
run_sql("""
CREATE INDEX IF NOT EXISTS idx_mv_olist_customer_features_monetary_nulls_last
    ON mv_olist_customer_features (monetary DESC NULLS LAST);
""")

top_plan_2 = explain(MV_TOP_N)
print('\n'.join(top_plan_2))

Limit  (cost=0.42..1.53 rows=10 width=126) (actual time=0.018..0.026 rows=10 loops=1)
  Buffers: shared hit=9 read=3
  ->  Index Scan using idx_mv_olist_customer_features_monetary_nulls_last on mv_olist_customer_features  (cost=0.42..11043.53 rows=99441 width=126) (actual time=0.017..0.024 rows=10 loops=1)
        Buffers: shared hit=9 read=3
Planning:
  Buffers: shared hit=15 read=1
Planning Time: 0.137 ms
Execution Time: 0.035 ms

Індекс `(monetary DESC NULLS LAST)` збігається з `ORDER BY`, і план став `Limit` над `Index Scan`: читаються перші 10 записів індексу замість усієї MV, і час падає з 12 мс до 0,035 мс. Інший варіант - писати `ORDER BY monetary DESC` без `NULLS LAST`, адже `COALESCE` у pipeline гарантує, що `NULL` у `monetary` немає.

### 5.5. Скільки коштує кожна ознака

Кожен stage виконується окремо через ті самі CTE: ті, на які запит не посилається, PostgreSQL не обчислює. Кожен сценарій запускається тричі, і в таблицю йдуть медіана часу та ключові вузли плану. Мілісекунди залежать від машини, порівнювати варто співвідношення.

In [30]:
def plan_summary(plan: list[str]) -> tuple[float, str]:
    ms = float(re.search(r'Execution Time: ([0-9.]+) ms', '\n'.join(plan)).group(1))
    nodes = []
    for line in plan:
        m = re.match(r'\s*(?:->\s*)?([A-Z][A-Za-z ]+?)(?: on | using |  \(|\s*\()', line)
        if not m:
            continue
        name = re.sub(r'^(?:Parallel|Partial|Finalize) ', '', m.group(1))
        if name not in nodes:
            nodes.append(name)
    key = [n for n in nodes if n in ('Gather', 'Gather Merge', 'WindowAgg', 'Sort', 'Incremental Sort',
                                     'HashAggregate', 'GroupAggregate', 'Hash Join', 'Hash Right Join',
                                     'Merge Join', 'Nested Loop', 'Seq Scan', 'Index Scan',
                                     'Index Only Scan', 'CTE Scan', 'Limit')]
    return ms, ', '.join(key)


scenarios = {
    'stage 1: сума замовлення': STAGE_CTES + " SELECT COUNT(*), SUM(order_total) FROM stage1_orders_total",
    'stages 0-3: RFM + cohort': STAGE_CTES + " SELECT COUNT(*), MAX(cohort_quarter), SUM(monetary) FROM stage3_cohort",
    'stage 4: rolling AOV 30d': STAGE_CTES + " SELECT COUNT(*), SUM(avg_order_value_30d) FROM stage4_rolling_aov WHERE rn_recent = 1",
    'stage 5: cancellation rate': STAGE_CTES + " SELECT COUNT(*), SUM(cancellation_rate) FROM stage5_cancel_rate",
    'stages 6-7: preferred category': STAGE_CTES + " SELECT COUNT(*), SUM(category_revenue) FROM stage7_preferred_category",
    'повний pipeline': FEATURE_PIPELINE,
    'MV: lookup за customer_id': MV_LOOKUP,
    'MV: top-10 за monetary': MV_TOP_N,
}

rows = []
for name, sql in scenarios.items():
    times = []
    for _ in range(3):
        ms, nodes = plan_summary(explain(sql))
        times.append(ms)
    rows.append((name, round(pd.Series(times).median(), 3), nodes))
costs = pd.DataFrame(rows, columns=['сценарій', 'median_ms', 'ключові вузли плану'])

full_ms = costs.loc[costs['сценарій'] == 'повний pipeline', 'median_ms'].iat[0]
lookup_ms = costs.loc[costs['сценарій'] == 'MV: lookup за customer_id', 'median_ms'].iat[0]
ratio = f'{full_ms / lookup_ms:,.0f}'.replace(',', ' ')
print(f'час повного pipeline / час lookup з MV: {ratio}')
with pd.option_context('display.max_colwidth', 200):
    display(costs)

час повного pipeline / час lookup з MV: 114 036

                         сценарій  median_ms                                                                                                                                      ключові вузли плану
0        stage 1: сума замовлення    241.144                                                                       GroupAggregate, Gather Merge, Sort, Hash Join, Hash Right Join, Seq Scan, CTE Scan
1        stages 0-3: RFM + cohort    343.600                                           GroupAggregate, Gather Merge, Sort, Hash Join, Hash Right Join, Seq Scan, HashAggregate, Nested Loop, CTE Scan
2        stage 4: rolling AOV 30d    388.479                                          GroupAggregate, Gather Merge, Sort, Hash Join, Hash Right Join, Seq Scan, WindowAgg, Incremental Sort, CTE Scan
3      stage 5: cancellation rate    301.417                                                        GroupAggregate, Gather Merge, Sort, Hash Join, Hash Right Join, Seq Scan, HashAggregate, CTE Scan
4  stages 6-7: preferred category    284.082                                                    GroupAggregate, Gather Merge, Sort, Hash Join, Hash Right Join, Seq Scan, WindowAgg, Incremental Sort
5                 повний pipeline   1254.394  GroupAggregate, Gather Merge, Sort, Hash Join, Hash Right Join, Seq Scan, Index Scan, HashAggregate, Nested Loop, CTE Scan, WindowAgg, Incremental Sort
6       MV: lookup за customer_id      0.011                                                                                                          Nested Loop, Limit, Index Only Scan, Index Scan
7          MV: top-10 за monetary      0.007                                                                                                                                        Limit, Index Scan

Один `EXPLAIN` повного pipeline тривав 1,6 с. Stage 1 у плані окремий вузол `CTE stage1_orders_total`: `Parallel Seq Scan` трьох таблиць, два `Parallel Hash Join`, `Sort` з external merge на диск і `GroupAggregate` до замовлення. RFM і cancellation rate рахує `HashAggregate` над `CTE Scan`, і обидва не вміщаються у `work_mem`: 21 batch і 7376 та 7168 кБ на диску. Для rolling AOV план має два `WindowAgg`, і `Sort` перед одним із них пише на диск 9448 кБ. Preferred category заново з'єднує чотири таблиці, разом із `Seq Scan` по `olist_products`. Гілки зводить ланцюжок `Merge Left Join`, а клієнтів читає `Index Scan` за `idx_olist_customers_unique_id`. Lookup з MV - це `Index Scan using idx_mv_olist_customer_features_customer_id` по 8 сторінках буфера за 0,065 мс.

За медіанами з таблиці stage 1 сам коштує 241 мс, і всі ознаки, крім preferred category, будуються поверх нього. Найдорожча окрема ознака rolling AOV, 388 мс. RFM з cohort коштує 344 мс, cancellation rate 301 мс. Preferred category, 284 мс, обходиться без stage 1 і повторює з'єднання сама. Повний pipeline за медіаною триває 1,25 с, а lookup з MV швидший на п'ять порядків.

## Reflection

Найдорожча окрема ознака - rolling AOV: 388 мс за медіаною проти 241 мс для самого stage 1. Поверх stage 1 вона додає два сортування і два `WindowAgg`, і одне сортування не вміщається в пам'ять та пише на диск 9448 кБ. Сам stage 1 теж недешевий: `Parallel Seq Scan` трьох таблиць, `Parallel Hash Join` і `Sort` на диску перед `GroupAggregate`. RFM і cancellation rate обходяться одним `HashAggregate` над `CTE Scan`, хоча й він не вміщається у `work_mem` і ділиться на 21 batch.

Кешувати варто весь набір ознак, а не одну. Повний pipeline займає 1,25 с, а lookup з MV - це `Index Scan` по 8 сторінках буфера за соті частки мілісекунди. Якщо замовлення надходять нічним пакетом, для batch-моделі достатньо щодобового `REFRESH ... CONCURRENTLY` після завантаження, а on-demand refresh потрібен після великого дозавантаження чи масової зміни статусів. Читання під час refresh не блокується.

Звичайний `VIEW` кращий, коли кожен запит має бачити поточний стан: оперативна перевірка статусів замовлень або ad-hoc аналіз, поки визначення ознак ще змінюються. Перевірка свіжості показала, що MV до refresh віддає старий `cancellation_rate`, а `VIEW` порахував би його заново.

Recursive CTE завершується, коли recursive part не повертає нових рядків. Якщо A запрошує B, а B запрошує A, нові рядки з'являються безкінечно. Перевірка `NOT id = ANY(path_ids)` не пускає у вже відвіданий вузол, `depth < 50` зупиняє обхід навіть за помилки в цій перевірці, а `CYCLE` позначає повтор вбудованим механізмом.

Найважливіші тут latency і recompute-cost: модель читає ознаки часто, а дані оновлюються пакетами. Storage-cost малий, MV займає 17 МБ плюс кілька мегабайтів індексів. Якби ознаки живили онлайн-модель, що реагує на кожне замовлення, головною стала б freshness, і MV довелося б замінити інкрементним оновленням таблиці ознак.